### ISSUE TITLE
How can i use cypiripi with existing bam files to start with?

### ISSUE THREAD

**Issue by gpcr** [sfu-compbio/cypiripi#2]
I have bwa-mem aligned bams to start with is there a work around to use cypiripi?

**Comment by gpcr** [comment]
surprized, with out a solution and closed it?

**Comment by inumanag** [comment]
Cypiripi has been discontinued. Please use [Aldy](https://github.com/inumanag/aldy) instead.

**Comment by gpcr** [comment]
Thanks
